name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Increment patch version
    - name: Increment Patch Version
      run: |
        mvn build-helper:parse-version versions:set \
          -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} \
          versions:commit

        new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "$new_version" >> $GITHUB_ENV

    # Build and push Docker image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push to Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: rif281/simple_java:${{ env.new_version }}

    # # Login to Docker Hub
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # # Push the Docker image
    # - name: Push Image
    #   run: |
    #     docker push your-registry-username/repository-name:$new_version
